---
- name: Aprovisionar Laboratorio Game Center en Workstation 1
  hosts: ws1
  gather_facts: no

  tasks:
    - name: "Crear VMs del Game Center"
      community.vmware.vmware_guest:
        hostname: "{{ ansible_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        template: "{{ item.template }}"
        datastore: "datastore1"
        folder: "/"
        state: poweredon
        guest_id: "{{ item.guest_id }}"
      loop:
        - { name: 'pfSense-Router-GameCenter', template: 'pfsense-template', guest_id: 'freebsd64Guest' }
        - { name: 'Server-Almalinux-GameCenter', template: 'almalinux-template', guest_id: 'almalinux_64Guest' }
        - { name: 'Cliente-Win11-GameCenter-01', template: 'windows11-home-template', guest_id: 'windows11_64Guest' }

- name: Aprovisionar Laboratorio Académico en Workstation 2
  hosts: ws2
  gather_facts: no

  tasks:
    - name: "Crear VMs del Laboratorio Académico"
      community.vmware.vmware_guest:
        hostname: "{{ ansible_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        template: "{{ item.template }}"
        datastore: "datastore1"
        folder: "/"
        state: poweredon
        guest_id: "{{ item.guest_id }}"
      loop:
        - { name: 'pfSense-Router-Academic', template: 'pfsense-template', guest_id: 'freebsd64Guest' }
        - { name: 'Server-Almalinux-Academic', template: 'almalinux-template', guest_id: 'almalinux_64Guest' }
        - { name: 'Cliente-Win11-Academic-01', template: 'windows11-home-template', guest_id: 'windows11_64Guest' }